# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: '3.0.x SDK'
  inputs:
    version: '3.0.x'

- task: UseDotNet@2
  displayName: '2.2.x runtime'
  inputs:
    version: '2.2.x'
    packageType: runtime

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1
  displayName: 'Publish to Azure'
  inputs:
    azureSubscription: 'Visual Studio Premium with MSDN(1af677c5-c06b-4b6a-9362-76ad386346ad)'
    appType: 'webApp'
    appName: 'sparrowhawk-pipelines-dotnet-core'
    package: '$(Build.ArtifactStagingDirectory)/*.zip'
    deploymentMethod: 'auto'
